import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col justify-between items-center p-24 min-h-[100vh] bg-gray-100">
        <div className="flex justify-between items-center w-full z-10 text-sm font-mono">
          <p>
            <span className="font-bold">MongoDB</span> Text Search
          </p>
          <div>
            <a href="https:flolu.de" target="_blank" rel="noopener noreferrer">
              By <span className="font-bold">Florian Ludewig</span>
            </a>
          </div>
        </div>

        <div className="flex justify-center items-center relative px-16 leading-6">Search</div>

        <div className="">
          <a href="https://github.com/flolu/mongo-search" target="_blank" rel="noopener noreferrer">
            <p>Source Code</p>
          </a>
        </div>
      </main>
    </>
  )
}
